### ISSUE TITLE
PR Creation Broken

### ISSUE THREAD

**Issue by ftalburt** [derberg/global-workflows-support#10]
PR creation is broken as of version 0.0.9. Root cause of the issue seems to be that `repo.defaultBranch` is being passed to `createPr`, but that property is undefined. The correct property (and what was previously used) is `repo.defaultBranchRef.name`.

https://github.com/derberg/global-workflows-support/blob/30750149bf2268645e2941c0676b18b9b87a05d6/lib/index.js#L66

**Comment by derberg** [comment]
@ftalburt hey, finally found time to fix it. Please use [v0.1.0](https://github.com/derberg/global-workflows-support/releases/tag/v0.1.0)
I also added some more debug logs.

Sorry for keeping you waiting. Please let me know where do you use this action.

It may sound strange but I'm not happy community of users for this action grows. This should be natively supported by GitHub and I want to try again to put some pressure on them on how important it is.
