### ISSUE TITLE
Changing the file name's of other workflows breaks this workflow

### ISSUE THREAD

**Issue by Chris-Softrams** [derberg/global-workflows-support#11]
#### Describe the bug
For reasons(lol) I changed some of our file names and it seems to have broke this workflow.
Example:
Prior filename `autoapprove.yml` new file name `auto-approve.yaml`

#### How to Reproduce
See above to rename the file

Then we get the following error:
`Error: Action failed because of: Error: ENOENT: no such file or directory, stat '/home/runner/work/template/template/.github/workflows/autoapprove.yml'`

#### Expected behavior
No errors and files are updated in all repos.

**Comment by derberg** [comment]
@Chris-Softrams sorry for such a late response.

Can you provide more logs. From logs before the error log I can easily spot at what stage the error happened. So basically what logs displayed before the error one.

For now I have no idea what that can be. Rename should not break it as the action doesn't read any workflow files, and it doesn't care about filenames

**Comment by derberg** [comment]
I worked

**Comment by derberg** [comment]
@Chris-Softrams I worked yesterday on https://github.com/derberg/global-workflows-support/releases/tag/v0.2.0 and was involved a lot in the code base because of needed refactor and I really have no idea where this error comes from. So just confirming I can't go any further here without more logs
