### ISSUE TITLE
Include additional files

### ISSUE THREAD

**Issue by ChipWolf** [derberg/global-workflows-support#21]
#### Reason/Context
We have a workflow that runs some pre-commit checks, this requires an additional file in the root of each repo.

#### Description
This could be implemented by adding a `files_to_include` option which would allow supplementary files to be included.

**Comment by derberg** [comment]
@ChipWolf hey, interesting feature! so how would it work? `files_to_include`? each file is picked, it the order it is added to the list and invoked? or? would it be a script file or what exactly?



or....wait, you mean make this workflow support more than `.github/workflows` located files?
