### ISSUE TITLE
Support more than 100 repos

### ISSUE THREAD

**Issue by Chris-Softrams** [derberg/global-workflows-support#9]
#### Reason/Context
Please try answering few of those questions
- Why we need this improvement? We are at 67 repos currently and adding more every week.
- How will this change help? We will continue to be able to use this workflow.
- What is the motivation? Global Workflows!!!!

**Comment by derberg** [comment]
oh yes, I knew someone will need it at some point in time. How many you add a week? so I know how much time left until you reach 100 😅

**Comment by Chris-Softrams** [comment]
@derberg we are at 68 right now, getting ready to add probably around 10-15 in the next 2 weeks.

**Comment by derberg** [comment]
@Chris-Softrams available with https://github.com/derberg/global-workflows-support/releases/tag/v0.4.0
